package fiscalsettingsusecases

import (
	"context"

	"fmt"

	fiscalsettingsentity "github.com/willjrcom/sales-backend-go/internal/domain/fiscal_settings"
	fiscalsettingsdto "github.com/willjrcom/sales-backend-go/internal/infra/dto/fiscal_settings"
	"github.com/willjrcom/sales-backend-go/internal/infra/repository/model"
	"github.com/willjrcom/sales-backend-go/internal/infra/service/focusnfe"
)

type Service struct {
	fiscalSettingsRepo model.FiscalSettingsRepository
	companyRepo        model.CompanyRepository
	focusClient        *focusnfe.Client
}

func NewService(fiscalSettingsRepo model.FiscalSettingsRepository, companyRepo model.CompanyRepository, focusClient *focusnfe.Client) *Service {
	return &Service{
		fiscalSettingsRepo: fiscalSettingsRepo,
		companyRepo:        companyRepo,
		focusClient:        focusClient,
	}
}

// GetFiscalSettings retrieves the fiscal settings for the company
func (s *Service) GetFiscalSettings(ctx context.Context) (*fiscalsettingsdto.FiscalSettingsDTO, error) {
	// Need company ID from context. Assuming companyRepo can get it or we extract from ctx.
	// Existing code used s.companyRepo.GetCompany(ctx) which likely uses user info in context.
	companyModel, err := s.companyRepo.GetCompany(ctx)
	if err != nil {
		return nil, err
	}

	settingsModel, err := s.fiscalSettingsRepo.GetByCompanyID(ctx, companyModel.ID)
	if err != nil {
		// If not found, return empty or default?
		// Or creating default settings?
		// For now, return empty DTO.
		return &fiscalsettingsdto.FiscalSettingsDTO{}, nil
	}

	if settingsModel == nil {
		return &fiscalsettingsdto.FiscalSettingsDTO{}, nil
	}

	settings := settingsModel.ToDomain()

	dto := &fiscalsettingsdto.FiscalSettingsDTO{}
	mapEntityToDTO(settings, dto)

	return dto, nil
}

// UpdateFiscalSettings updates or creates the fiscal settings for the company
func (s *Service) UpdateFiscalSettings(ctx context.Context, input *fiscalsettingsdto.FiscalSettingsUpdateDTO) error {
	companyModel, err := s.companyRepo.GetCompany(ctx)
	if err != nil {
		return err
	}

	// Check if exists
	existingModel, _ := s.fiscalSettingsRepo.GetByCompanyID(ctx, companyModel.ID)

	var settings *fiscalsettingsentity.FiscalSettings
	if existingModel != nil {
		settings = existingModel.ToDomain()
	} else {
		settings = fiscalsettingsentity.NewFiscalSettings(companyModel.ID)
	}

	// Update fields
	updateEntityFromDTO(settings, input)

	settingsModel := &model.FiscalSettings{}
	settingsModel.FromDomain(settings)

	if existingModel == nil {
		// Create
		// Ensure ID is correct if generated by domain NewEntity
		settingsModel.ID = settings.ID

		if err := s.fiscalSettingsRepo.Create(ctx, settingsModel); err != nil {
			return err
		}
	} else {
		// Update
		settingsModel.ID = existingModel.ID
		if err := s.fiscalSettingsRepo.Update(ctx, settingsModel); err != nil {
			return err
		}
	}

	if settings.IsActive {
		if err := s.registerCompanyInFocus(ctx, settings); err != nil {
			return err
		}
	}

	return nil
}

func (s *Service) registerCompanyInFocus(ctx context.Context, settings *fiscalsettingsentity.FiscalSettings) error {
	if s.focusClient == nil || !s.focusClient.Enabled() {
		return fmt.Errorf("focus nfe client is not enabled")
	}

	regime := "1" // Simples Nacional
	if settings.TaxRegime == 3 {
		regime = "3" // Regime Normal
	}

	req := &focusnfe.CompanyRegistryRequest{
		Nome:                    settings.BusinessName,
		NomeFantasia:            settings.TradeName,
		InscricaoEstadual:       settings.StateRegistration,
		InscricaoMunicipal:      settings.MunicipalRegistration,
		CNPJ:                    settings.Cnpj,
		RegimeTributario:        regime,
		Email:                   settings.Email,
		Telefone:                settings.Phone,
		Logradouro:              settings.Address.Street,
		Numero:                  settings.Address.Number,
		Complemento:             settings.Address.Complement,
		Bairro:                  settings.Address.Neighborhood,
		CEP:                     settings.Address.Cep,
		Municipio:               settings.Address.City,
		UF:                      settings.Address.UF,
		DiscriminaImpostos:      settings.ShowTaxBreakdown,
		EnviarEmailDestinatario: settings.SendEmailToRecipient,
	}

	resp, err := s.focusClient.CadastrarEmpresa(ctx, req)
	if err != nil {
		return fmt.Errorf("failed to register company in Focus NFe: %w", err)
	}

	// Update settings with the returned ID if successful
	if resp != nil && resp.ID > 0 {
		settings.SetCompanyRegistryID(resp.ID)

		settingsModel := &model.FiscalSettings{}
		settingsModel.FromDomain(settings)

		// Update DB with the new ID
		if err := s.fiscalSettingsRepo.Update(ctx, settingsModel); err != nil {
			return fmt.Errorf("failed to update company registry id: %w", err)
		}
	}

	return nil
}

func mapEntityToDTO(entity *fiscalsettingsentity.FiscalSettings, dto *fiscalsettingsdto.FiscalSettingsDTO) {
	dto.FiscalEnabled = entity.IsActive
	dto.StateRegistration = entity.StateRegistration
	dto.TaxRegime = entity.TaxRegime
	dto.CNAE = entity.CNAE
	dto.CRT = entity.CRT
	dto.IsSimpleNational = entity.IsSimpleNational
	dto.MunicipalRegistration = entity.MunicipalRegistration
	dto.ShowTaxBreakdown = entity.ShowTaxBreakdown
	dto.SendEmailToRecipient = entity.SendEmailToRecipient
	dto.BusinessName = entity.BusinessName
	dto.TradeName = entity.TradeName
	dto.Cnpj = entity.Cnpj
	dto.Email = entity.Email
	dto.Phone = entity.Phone
	dto.Street = entity.Address.Street
	dto.Number = entity.Address.Number
	dto.Complement = entity.Address.Complement
	dto.Neighborhood = entity.Address.Neighborhood
	dto.City = entity.Address.City
	dto.UF = entity.Address.UF
	dto.Cep = entity.Address.Cep
}

func updateEntityFromDTO(entity *fiscalsettingsentity.FiscalSettings, dto *fiscalsettingsdto.FiscalSettingsUpdateDTO) {
	if dto.FiscalEnabled != nil {
		entity.IsActive = *dto.FiscalEnabled
	}
	if dto.StateRegistration != nil {
		entity.StateRegistration = *dto.StateRegistration
	}
	if dto.TaxRegime != nil {
		entity.TaxRegime = *dto.TaxRegime
		entity.IsSimpleNational = entity.TaxRegime == 1 || entity.TaxRegime == 2
	}
	if dto.CNAE != nil {
		entity.CNAE = *dto.CNAE
	}
	if dto.CRT != nil {
		entity.CRT = *dto.CRT
	}
	if dto.MunicipalRegistration != nil {
		entity.MunicipalRegistration = *dto.MunicipalRegistration
	}
	if dto.ShowTaxBreakdown != nil {
		entity.ShowTaxBreakdown = *dto.ShowTaxBreakdown
	}
	if dto.SendEmailToRecipient != nil {
		entity.SendEmailToRecipient = *dto.SendEmailToRecipient
	}
	if dto.BusinessName != nil {
		entity.BusinessName = *dto.BusinessName
	}
	if dto.TradeName != nil {
		entity.TradeName = *dto.TradeName
	}
	if dto.Cnpj != nil {
		entity.Cnpj = *dto.Cnpj
	}
	if dto.Email != nil {
		entity.Email = *dto.Email
	}
	if dto.Phone != nil {
		entity.Phone = *dto.Phone
	}
	if dto.Street != nil {
		entity.Address.Street = *dto.Street
	}
	if dto.Number != nil {
		entity.Address.Number = *dto.Number
	}
	if dto.Complement != nil {
		entity.Address.Complement = *dto.Complement
	}
	if dto.Neighborhood != nil {
		entity.Address.Neighborhood = *dto.Neighborhood
	}
	if dto.City != nil {
		entity.Address.City = *dto.City
	}
	if dto.UF != nil {
		entity.Address.UF = *dto.UF
	}
	if dto.Cep != nil {
		entity.Address.Cep = *dto.Cep
	}
}
