version: '2.0'
services:
  go-app:
    name: "go-app"
    image: "go-app-image"
    build:
      context: .  # Usar o Dockerfile atual para construir a imagem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expondo a porta do Go HTTP server

    command: ["go", "run", "main.go", "httpserver"]  # Comando para rodar o Go app
    networks:
      - go-network
    restart: always  # Garante que o container reinicie automaticamente

networks:
  go-network:
    driver: bridge
