// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package quantityusecases

import (
	"github.com/willjrcom/sales-backend-go/bootstrap/database"
	categoryrepositorylocal "github.com/willjrcom/sales-backend-go/internal/infra/repository/local/product_category"
	quantityrepositorylocal "github.com/willjrcom/sales-backend-go/internal/infra/repository/local/quantity"
	productcategoryrepositorybun "github.com/willjrcom/sales-backend-go/internal/infra/repository/postgres/product_category"
	quantityrepositorybun "github.com/willjrcom/sales-backend-go/internal/infra/repository/postgres/quantity"
)

// Injectors from wire.go:

func InitializeService() (*Service, error) {
	db := database.NewPostgreSQLConnection()
	quantityRepository := quantityrepositorybun.NewQuantityRepositoryBun(db)
	categoryRepository := productcategoryrepositorybun.NewProductCategoryRepositoryBun(db)
	service := NewService(quantityRepository, categoryRepository)
	return service, nil
}

func InitializeServiceForTest() (*Service, error) {
	quantityRepository := quantityrepositorylocal.NewQuantityRepositoryLocal()
	categoryRepository := categoryrepositorylocal.NewCategoryRepositoryLocal()
	service := NewService(quantityRepository, categoryRepository)
	return service, nil
}
