// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package productcategoryusecases

import (
	"github.com/willjrcom/sales-backend-go/bootstrap/database"
	"github.com/willjrcom/sales-backend-go/internal/infra/repository/local/category"
	"github.com/willjrcom/sales-backend-go/internal/infra/repository/postgres/product_category"
	"github.com/willjrcom/sales-backend-go/internal/usecases/quantity"
	"github.com/willjrcom/sales-backend-go/internal/usecases/size"
)

// Injectors from wire.go:

func InitializeService() (*Service, error) {
	db := database.NewPostgreSQLConnection()
	categoryRepository := productcategoryrepositorybun.NewProductCategoryRepositoryBun(db)
	service, err := quantityusecases.InitializeService()
	if err != nil {
		return nil, err
	}
	sizeusecasesService, err := sizeusecases.InitializeService()
	if err != nil {
		return nil, err
	}
	productcategoryusecasesService := NewService(categoryRepository, service, sizeusecasesService)
	return productcategoryusecasesService, nil
}

func InitializeServiceForTest() (*Service, error) {
	categoryRepository := categoryrepositorylocal.NewCategoryRepositoryLocal()
	service, err := quantityusecases.InitializeServiceForTest()
	if err != nil {
		return nil, err
	}
	sizeusecasesService, err := sizeusecases.InitializeServiceForTest()
	if err != nil {
		return nil, err
	}
	productcategoryusecasesService := NewService(categoryRepository, service, sizeusecasesService)
	return productcategoryusecasesService, nil
}
