// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package productcategoryusecases

import (
	"github.com/willjrcom/sales-backend-go/bootstrap/database"
	productcategoryrepositorylocal "github.com/willjrcom/sales-backend-go/internal/infra/repository/local/product_category"
	productcategoryrepositorybun "github.com/willjrcom/sales-backend-go/internal/infra/repository/postgres/product_category"
	sizeusecases "github.com/willjrcom/sales-backend-go/internal/usecases/size"
)

// Injectors from wire.go:

func InitializeService() (*Service, error) {
	db := database.NewPostgreSQLConnection()
	categoryRepository := productcategoryrepositorybun.NewProductCategoryRepositoryBun(db)

	sizeusecasesService, err := sizeusecases.InitializeService()
	if err != nil {
		return nil, err
	}
	productcategoryusecasesService := NewService(categoryRepository, sizeusecasesService)
	return productcategoryusecasesService, nil
}

func InitializeServiceForTest() (*Service, error) {
	categoryRepository := productcategoryrepositorylocal.NewCategoryRepositoryLocal()

	sizeusecasesService, err := sizeusecases.InitializeServiceForTest()
	if err != nil {
		return nil, err
	}
	productcategoryusecasesService := NewService(categoryRepository, sizeusecasesService)
	return productcategoryusecasesService, nil
}
