// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package productcategoryproductusecases

import (
	"github.com/willjrcom/sales-backend-go/bootstrap/database"
	"github.com/willjrcom/sales-backend-go/internal/infra/repository/postgres/product_category"
	"github.com/willjrcom/sales-backend-go/internal/infra/repository/postgres/product_category_product"
	"github.com/willjrcom/sales-backend-go/internal/infra/service/s3"
)

// Injectors from wire.go:

func InitializeService() (*Service, error) {
	db := database.NewPostgreSQLConnection()
	productRepositoryBun := productcategoryproductrepositorybun.NewProductRepositoryBun(db)
	productCategoryRepositoryBun := productcategoryrepositorybun.NewProductCategoryRepositoryBun(db)
	s3Client := s3service.NewS3Client()
	service := NewService(productRepositoryBun, productCategoryRepositoryBun, s3Client)
	return service, nil
}
